
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "openToMeetups" BOOLEAN DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS experience TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "openToMentoring" BOOLEAN DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS twitter TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS youtube TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicWinRate" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicPnl" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicTrades" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicLocation" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS tagline TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "displayName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "primaryAssets" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tradingStyle" TEXT;
